{{
    config(
        materialized='table',
        partition_by={
            "field": "data_year",
            "data_type": "int64",
            "range": {"start":2013, "end":2030, "interval":1}
        },
        cluster_by=["prescriber_npi"],
        meta={"dagster": {"group": "silver"}},
    )
}}

select
    CAST(PRSCRBR_NPI as INT64) as prescriber_npi,
    Prscrbr_Last_Org_Name as prescriber_last_name,
    Prscrbr_First_Name as prescriber_first_name,
    Prscrbr_MI as prescriber_middle_initial,
    Prscrbr_Crdntls as prescriber_credentials,
    Prscrbr_Ent_Cd as prescriber_entity_code,
    Prscrbr_St1 as prescriber_address_line1,
    Prscrbr_St2 as prescriber_address_line2,
    Prscrbr_City as prescriber_city,
    Prscrbr_State_Abrvtn as prescriber_state,
    Prscrbr_State_FIPS as prescriber_state_FIPS_code,
    Prscrbr_zip5 as prescriber_zip_code,
    Prscrbr_RUCA as prescriber_rural_urban_commuting_area_code,
    Prscrbr_RUCA_Desc as prescriber_rural_urban_commuting_area_desc,
    Prscrbr_Cntry as prescriber_country,
    Prscrbr_Type as prescriber_specialty_type,
    Prscrbr_Type_src as prescriber_specialty_type_source,
    CAST(Tot_Clms as INT64) as total_medicare_part_d_claim_count,
    CAST(Tot_30day_Fills as INT64) as total_medicare_part_d_30day_fills,
    Tot_Drug_Cst as total_medicare_part_d_total_drug_cost,
    CAST(Tot_Day_Suply as INT64) as total_medicare_part_d_total_days_supply,
    CAST(Tot_Benes as INT64) as total_medicare_part_d_unique_beneficiary_count,
    GE65_Sprsn_Flag as greater_than_65_claim_suppression_reason,
    CAST(GE65_Tot_Clms as INT64) as greater_than_65_medicare_part_d_claim_count,
    CAST(GE65_Tot_30day_Fills as INT64) as greater_than_65_medicare_part_d_30day_fills,
    GE65_Tot_Drug_Cst as greater_than_65_medicare_part_d_total_drug_cost,
    CAST(GE65_Tot_Day_Suply as INT64) as greater_than_65_medicare_part_d_total_days_supply,
    GE65_Bene_Sprsn_Flag as greater_than_65_beneficiary_suppression_reason,
    CAST(GE65_Tot_Benes as INT64) as greater_than_65_medicare_part_d_beneficiary_count,
    Brnd_Sprsn_Flag as brand_claim_suppression_reason,
    CAST(Brnd_Tot_Clms as INT64) as brand_medicare_part_d_claim_count,
    Brnd_Tot_Drug_Cst as brand_medicare_part_d_total_drug_cost,
    Gnrc_Sprsn_Flag as generic_claim_suppression_reason,
    CAST(Gnrc_Tot_Clms as INT64) as generic_medicare_part_d_claim_count,
    Gnrc_Tot_Drug_Cst as generic_medicare_part_d_total_drug_cost,
    Othr_Sprsn_Flag as other_claim_suppression_reason,
    CAST(Othr_Tot_Clms as INT64) as other_medicare_part_d_claim_count,
    Othr_Tot_Drug_Cst as other_medicare_part_d_total_drug_cost,
    MAPD_Sprsn_Flag as medicare_advantage_part_d_suppression_reason,
    CAST(MAPD_Tot_Clms as INT64) as medicare_advantage_part_d_claim_count,
    MAPD_Tot_Drug_Cst as medicare_advantage_part_d_total_drug_cost,
    PDP_Sprsn_Flag as prescription_drug_plan_suppression_reason,
    CAST(PDP_Tot_Clms as INT64) as prescription_drug_plan_claim_count,
    PDP_Tot_Drug_Cst as prescription_drug_plan_total_drug_cost,
    LIS_Sprsn_Flag as low_income_subsidy_suppression_reason,
    CAST(LIS_Tot_Clms as INT64) as low_income_subsidy_claim_count,
    LIS_Drug_Cst as low_income_subsidy_total_drug_cost,
    NonLIS_Sprsn_Flag as non_low_income_subsidy_suppression_reason,
    CAST(NonLIS_Tot_Clms as INT64) as non_low_income_subsidy_claim_count,
    NonLIS_Drug_Cst as non_low_income_subsidy_total_drug_cost,
    CAST(Opioid_Tot_Clms as INT64) as opioid_total_claim_count,
    Opioid_Tot_Drug_Cst as opioid_total_drug_cost,
    CAST(Opioid_Tot_Suply as INT64) as opioid_total_days_supply,
    CAST(Opioid_Tot_Benes as INT64) as opioid_unique_beneficiary_count,
    Opioid_Prscrbr_Rate as prescriber_opioid_claim_percentage,
    CAST(Opioid_LA_Tot_Clms as INT64) as long_acting_opioid_total_claim_count,
    Opioid_LA_Tot_Drug_Cst as long_acting_opioid_total_drug_cost,
    CAST(Opioid_LA_Tot_Suply as INT64) as long_acting_opioid_total_days_supply,
    CAST(Opioid_LA_Tot_Benes as INT64) as long_acting_opioid_unique_beneficiary_count,
    Opioid_LA_Prscrbr_Rate as long_acting_opioid_claim_percentage,
    CAST(Antbtc_Tot_Clms as INT64) as antibiotic_total_claim_count,
    Antbtc_Tot_Drug_Cst as antibiotic_total_drug_cost,
    CAST(Antbtc_Tot_Benes as INT64) as antibiotic_unique_beneficiary_count,
    Antpsyct_GE65_Sprsn_Flag as antipsychotic_greater_than_65_claim_suppression_reason,
    CAST(Antpsyct_GE65_Tot_Clms as INT64) as antipsychotic_greater_than_65_total_claim_count,
    Antpsyct_GE65_Tot_Drug_Cst as antipsychotic_greater_than_65_total_drug_cost,
    Antpsyct_GE65_Bene_Suprsn_Flag as antipsychotic_greater_than_65_beneficiary_suppression_reason,
    CAST(Antpsyct_GE65_Tot_Benes as INT64) as antipsychotic_greater_than_65_unique_beneficiary_count,
    Bene_Avg_Age as beneficiary_average_age,
    CAST(Bene_Age_LT_65_Cnt as INT64) as beneficiary_age_less_than_65_count,
    CAST(Bene_Age_65_74_Cnt as INT64) as beneficiary_age_65_to_74_count,
    CAST(Bene_Age_75_84_Cnt as INT64) as beneficiary_age_75_to_84_count,
    CAST(Bene_Age_GT_84_Cnt as INT64) as beneficiary_age_greater_than_84_count,
    CAST(Bene_Feml_Cnt as INT64) as beneficiary_female_count,
    CAST(Bene_Male_Cnt as INT64) as beneficiary_male_count,
    CAST(Bene_Race_Wht_Cnt as INT64) as beneficiary_non_hispanic_white_count,
    CAST(Bene_Race_Black_Cnt as INT64) as beneficiary_non_hispanic_black_count,
    CAST(Bene_Race_Api_Cnt as INT64) as beneficiary_asian_pacific_isle_count,
    CAST(Bene_Race_Hspnc_Cnt as INT64) as beneficiary_hispanic_count,
    CAST(Bene_Race_Natind_Cnt as INT64) as beneficiary_native_american_alaskian_count,
    CAST(Bene_Race_Othr_Cnt as INT64) as beneficiary_other_race_count,
    CAST(Bene_Dual_Cnt as INT64) as beneficiary_medicare_medicaid_entitlement_count,
    CAST(Bene_Ndual_Cnt as INT64) as beneficiary_medicare_only_count,
    Bene_Avg_Risk_Scre as average_hierarchical_condition_category_risk_score,
    CAST(data_year as INT64) as data_year,
    loaded_at
from
    {{  source('part_d_raw', 'raw_data') }}
