version: 2

sources:
  - name: part_d_raw
    database: "{{ env_var('GCP_PROJECT') }}"
    schema: "{{ env_var('GCP_RAW_DATASET') }}"
    tables:
      - name: "{{ env_var('GCP_RAW_TABLE') }}"
        loaded_at_field: loaded_at

models:
  - name: part_d_silver
    columns:
      - name: prescriber_npi
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - prescriber_npi
            - data_year

